export interface IEmployee {
  id: string;
  name: string;
  position: string;
  team: string;
  office_location: string;
  office_location_country: string;
}

export const EmployeeData: IEmployee[] = [
  {
    id: '001',
    name: 'Alice Johnson',
    position: 'Software Engineer',
    team: 'Development',
    office_location: 'New York',
    office_location_country: 'USA',
  },
  {
    id: '002',
    name: 'Bob Smith',
    position: 'Product Manager',
    team: 'Product',
    office_location: 'San Francisco',
    office_location_country: 'USA',
  },
  {
    id: '003',
    name: 'Carol Lee',
    position: 'UX Designer',
    team: 'Design',
    office_location: 'Toronto',
    office_location_country: 'Canada',
  },
  {
    id: '004',
    name: 'David Brown',
    position: 'Data Analyst',
    team: 'Analytics',
    office_location: 'London',
    office_location_country: 'UK',
  },
  {
    id: '005',
    name: 'Eva White',
    position: 'Marketing Specialist',
    team: 'Marketing',
    office_location: 'Sydney',
    office_location_country: 'Australia',
  },
  {
    id: '006',
    name: 'Frank Green',
    position: 'Sales Representative',
    team: 'Sales',
    office_location: 'Berlin',
    office_location_country: 'Germany',
  },
  {
    id: '007',
    name: 'Grace Black',
    position: 'HR Coordinator',
    team: 'Human Resources',
    office_location: 'Tokyo',
    office_location_country: 'Japan',
  },
  {
    id: '008',
    name: 'Henry Miller',
    position: 'Project Manager',
    team: 'Operations',
    office_location: 'Paris',
    office_location_country: 'France',
  },
  {
    id: '009',
    name: 'Isla Garcia',
    position: 'Content Writer',
    team: 'Content',
    office_location: 'Madrid',
    office_location_country: 'Spain',
  },
  {
    id: '010',
    name: 'Jake Taylor',
    position: 'DevOps Engineer',
    team: 'IT',
    office_location: 'Bangalore',
    office_location_country: 'India',
  },
  {
    id: '011',
    name: 'Lily Martinez',
    position: 'Customer Support',
    team: 'Support',
    office_location: 'Cape Town',
    office_location_country: 'South Africa',
  },
  {
    id: '012',
    name: 'Mark Wilson',
    position: 'Business Analyst',
    team: 'Strategy',
    office_location: 'Singapore',
    office_location_country: 'Singapore',
  },
  {
    id: '013',
    name: 'Nina Scott',
    position: 'QA Tester',
    team: 'Quality Assurance',
    office_location: 'Amsterdam',
    office_location_country: 'Netherlands',
  },
  {
    id: '014',
    name: 'Oliver Harris',
    position: 'Finance Manager',
    team: 'Finance',
    office_location: 'Zurich',
    office_location_country: 'Switzerland',
  },
  {
    id: '015',
    name: 'Paula Lewis',
    position: 'Community Manager',
    team: 'Community',
    office_location: 'Dublin',
    office_location_country: 'Ireland',
  },
  {
    id: '016',
    name: 'Quinn Patel',
    position: 'Network Engineer',
    team: 'IT',
    office_location: 'Dubai',
    office_location_country: 'UAE',
  },
  {
    id: '017',
    name: 'Rita Kim',
    position: 'Social Media Manager',
    team: 'Marketing',
    office_location: 'Los Angeles',
    office_location_country: 'USA',
  },
  {
    id: '018',
    name: 'Sam Chen',
    position: 'Graphic Designer',
    team: 'Design',
    office_location: 'Shanghai',
    office_location_country: 'China',
  },
  {
    id: '019',
    name: 'Tina Rogers',
    position: 'Operations Manager',
    team: 'Operations',
    office_location: 'Seattle',
    office_location_country: 'USA',
  },
  {
    id: '020',
    name: 'Ulysses Adams',
    position: 'Research Scientist',
    team: 'R&D',
    office_location: 'Boston',
    office_location_country: 'USA',
  },
  {
    id: '021',
    name: 'Vera Martinez',
    position: 'Legal Advisor',
    team: 'Legal',
    office_location: 'Toronto',
    office_location_country: 'Canada',
  },
  {
    id: '022',
    name: 'Will Bennett',
    position: 'SEO Specialist',
    team: 'Marketing',
    office_location: 'Chicago',
    office_location_country: 'USA',
  },
  {
    id: '023',
    name: 'Xena Collins',
    position: 'Account Manager',
    team: 'Sales',
    office_location: 'Melbourne',
    office_location_country: 'Australia',
  },
  {
    id: '024',
    name: 'Yusuf Elmas',
    position: 'Web Developer',
    team: 'Development',
    office_location: 'Istanbul',
    office_location_country: 'Turkey',
  },
  {
    id: '025',
    name: 'Zara Thompson',
    position: 'Content Strategist',
    team: 'Content',
    office_location: 'Vancouver',
    office_location_country: 'Canada',
  },
  {
    id: '026',
    name: 'Alex Brooks',
    position: 'Cloud Engineer',
    team: 'IT',
    office_location: 'Austin',
    office_location_country: 'USA',
  },
  {
    id: '027',
    name: 'Bella Robinson',
    position: 'Event Coordinator',
    team: 'Marketing',
    office_location: 'Atlanta',
    office_location_country: 'USA',
  },
  {
    id: '028',
    name: 'Cody Reed',
    position: 'Market Researcher',
    team: 'Analytics',
    office_location: 'Houston',
    office_location_country: 'USA',
  },
  {
    id: '029',
    name: 'Diana Mitchell',
    position: 'Product Designer',
    team: 'Design',
    office_location: 'Berlin',
    office_location_country: 'Germany',
  },
  {
    id: '030',
    name: 'Ethan Rivera',
    position: 'Mobile Developer',
    team: 'Development',
    office_location: 'Barcelona',
    office_location_country: 'Spain',
  },
  {
    id: '031',
    name: 'Fiona Chen',
    position: 'Corporate Trainer',
    team: 'Human Resources',
    office_location: 'Singapore',
    office_location_country: 'Singapore',
  },
  {
    id: '032',
    name: 'George Lee',
    position: 'Logistics Coordinator',
    team: 'Operations',
    office_location: 'London',
    office_location_country: 'UK',
  },
  {
    id: '033',
    name: 'Hannah Kim',
    position: 'User Researcher',
    team: 'Design',
    office_location: 'Tokyo',
    office_location_country: 'Japan',
  },
  {
    id: '034',
    name: 'Isaac Clark',
    position: 'Content Editor',
    team: 'Content',
    office_location: 'Montreal',
    office_location_country: 'Canada',
  },
  {
    id: '035',
    name: 'Jasmine Young',
    position: 'Brand Manager',
    team: 'Marketing',
    office_location: 'Paris',
    office_location_country: 'France',
  },
  {
    id: '036',
    name: 'Kevin Hall',
    position: 'Technical Writer',
    team: 'Content',
    office_location: 'Dublin',
    office_location_country: 'Ireland',
  },
  {
    id: '037',
    name: 'Luna Patel',
    position: 'Data Scientist',
    team: 'Analytics',
    office_location: 'Bangalore',
    office_location_country: 'India',
  },
  {
    id: '038',
    name: 'Michael King',
    position: 'Security Analyst',
    team: 'IT',
    office_location: 'Frankfurt',
    office_location_country: 'Germany',
  },
  {
    id: '039',
    name: 'Nora Scott',
    position: 'Sales Analyst',
    team: 'Sales',
    office_location: 'Austin',
    office_location_country: 'USA',
  },
  {
    id: '040',
    name: 'Oscar Green',
    position: 'Data Engineer',
    team: 'Development',
    office_location: 'San Francisco',
    office_location_country: 'USA',
  },
  {
    id: '041',
    name: 'Penny Adams',
    position: 'Compliance Officer',
    team: 'Legal',
    office_location: 'Melbourne',
    office_location_country: 'Australia',
  },
  {
    id: '042',
    name: 'Quincy Reed',
    position: 'Customer Success Manager',
    team: 'Support',
    office_location: 'Los Angeles',
    office_location_country: 'USA',
  },
  {
    id: '043',
    name: 'Rachel Brooks',
    position: 'E-commerce Specialist',
    team: 'Marketing',
    office_location: 'Toronto',
    office_location_country: 'Canada',
  },
  {
    id: '044',
    name: 'Samuel Gray',
    position: 'Technical Support',
    team: 'Support',
    office_location: 'Singapore',
    office_location_country: 'Singapore',
  },
  {
    id: '045',
    name: 'Tara Johnson',
    position: 'System Administrator',
    team: 'IT',
    office_location: 'Dubai',
    office_location_country: 'UAE',
  },
  {
    id: '046',
    name: 'Uriah Parker',
    position: 'Business Development Manager',
    team: 'Sales',
    office_location: 'Chicago',
    office_location_country: 'USA',
  },
  {
    id: '047',
    name: 'Vanessa Lee',
    position: 'Product Owner',
    team: 'Product',
    office_location: 'Amsterdam',
    office_location_country: 'Netherlands',
  },
  {
    id: '048',
    name: 'Walter Brown',
    position: 'Financial Analyst',
    team: 'Finance',
    office_location: 'Zurich',
    office_location_country: 'Switzerland',
  },
  {
    id: '049',
    name: 'Xander White',
    position: 'Talent Acquisition Specialist',
    team: 'Human Resources',
    office_location: 'Madrid',
    office_location_country: 'Spain',
  },
  {
    id: '050',
    name: 'Yara Martin',
    position: 'Web Analyst',
    team: 'Analytics',
    office_location: 'Barcelona',
    office_location_country: 'Spain',
  },
  {
    id: '051',
    name: 'Zoe Carter',
    position: 'Virtual Assistant',
    team: 'Support',
    office_location: 'Cape Town',
    office_location_country: 'South Africa',
  },
  {
    id: '052',
    name: 'Aaron Diaz',
    position: 'Community Engagement Manager',
    team: 'Community',
    office_location: 'Toronto',
    office_location_country: 'Canada',
  },
  {
    id: '053',
    name: 'Bella Lee',
    position: 'Supply Chain Manager',
    team: 'Operations',
    office_location: 'Berlin',
    office_location_country: 'Germany',
  },
  {
    id: '054',
    name: 'Carl Wong',
    position: 'Business Analyst',
    team: 'Strategy',
    office_location: 'Tokyo',
    office_location_country: 'Japan',
  },
  {
    id: '055',
    name: 'Diane Moore',
    position: 'Product Marketing Manager',
    team: 'Marketing',
    office_location: 'Paris',
    office_location_country: 'France',
  },
  {
    id: '056',
    name: 'Evan Hill',
    position: 'Software Architect',
    team: 'Development',
    office_location: 'New York',
    office_location_country: 'USA',
  },
  {
    id: '057',
    name: 'Fiona Evans',
    position: 'Digital Marketing Specialist',
    team: 'Marketing',
    office_location: 'Los Angeles',
    office_location_country: 'USA',
  },
  {
    id: '058',
    name: 'George Knight',
    position: 'HR Manager',
    team: 'Human Resources',
    office_location: 'San Francisco',
    office_location_country: 'USA',
  },
  {
    id: '059',
    name: 'Hannah Wright',
    position: 'Chief Financial Officer',
    team: 'Finance',
    office_location: 'Toronto',
    office_location_country: 'Canada',
  },
  {
    id: '060',
    name: 'Ian Scott',
    position: 'Quality Assurance Engineer',
    team: 'Quality Assurance',
    office_location: 'London',
    office_location_country: 'UK',
  },
  {
    id: '061',
    name: 'Jack Thompson',
    position: 'Network Administrator',
    team: 'IT',
    office_location: 'Dublin',
    office_location_country: 'Ireland',
  },
  {
    id: '062',
    name: 'Karen Perez',
    position: 'Copywriter',
    team: 'Content',
    office_location: 'Sydney',
    office_location_country: 'Australia',
  },
  {
    id: '063',
    name: 'Laura Rodriguez',
    position: 'Research Analyst',
    team: 'Analytics',
    office_location: 'Chicago',
    office_location_country: 'USA',
  },
  {
    id: '064',
    name: 'Mike Williams',
    position: 'Sales Engineer',
    team: 'Sales',
    office_location: 'Atlanta',
    office_location_country: 'USA',
  },
  {
    id: '065',
    name: 'Nina Foster',
    position: 'Product Analyst',
    team: 'Product',
    office_location: 'Bangalore',
    office_location_country: 'India',
  },
  {
    id: '066',
    name: 'Oscar Yang',
    position: 'Marketing Analyst',
    team: 'Marketing',
    office_location: 'Singapore',
    office_location_country: 'Singapore',
  },
  {
    id: '067',
    name: 'Penny Young',
    position: 'Database Administrator',
    team: 'IT',
    office_location: 'Toronto',
    office_location_country: 'Canada',
  },
  {
    id: '068',
    name: 'Quinn Lee',
    position: 'Event Planner',
    team: 'Marketing',
    office_location: 'New York',
    office_location_country: 'USA',
  },
  {
    id: '069',
    name: 'Raymond Chen',
    position: 'Product Support Specialist',
    team: 'Support',
    office_location: 'Berlin',
    office_location_country: 'Germany',
  },
  {
    id: '070',
    name: 'Sophie Khan',
    position: 'Graphic Artist',
    team: 'Design',
    office_location: 'Toronto',
    office_location_country: 'Canada',
  },
  {
    id: '071',
    name: 'Tommy Patel',
    position: 'IT Consultant',
    team: 'IT',
    office_location: 'Dubai',
    office_location_country: 'UAE',
  },
  {
    id: '072',
    name: 'Uma Smith',
    position: 'Account Executive',
    team: 'Sales',
    office_location: 'Chicago',
    office_location_country: 'USA',
  },
  {
    id: '073',
    name: 'Victor Cruz',
    position: 'SEO Manager',
    team: 'Marketing',
    office_location: 'Los Angeles',
    office_location_country: 'USA',
  },
  {
    id: '074',
    name: 'Wendy Garcia',
    position: 'Mobile App Developer',
    team: 'Development',
    office_location: 'Barcelona',
    office_location_country: 'Spain',
  },
  {
    id: '075',
    name: 'Xena Lopez',
    position: 'Product Development Lead',
    team: 'Product',
    office_location: 'Austin',
    office_location_country: 'USA',
  },
  {
    id: '076',
    name: 'Yasmin Williams',
    position: 'Customer Experience Manager',
    team: 'Support',
    office_location: 'Dublin',
    office_location_country: 'Ireland',
  },
  {
    id: '077',
    name: 'Zachary Evans',
    position: 'Research Associate',
    team: 'R&D',
    office_location: 'Tokyo',
    office_location_country: 'Japan',
  },
  {
    id: '078',
    name: 'Amy Brooks',
    position: 'Digital Designer',
    team: 'Design',
    office_location: 'Melbourne',
    office_location_country: 'Australia',
  },
  {
    id: '079',
    name: 'Brian Mitchell',
    position: 'Data Governance Analyst',
    team: 'Analytics',
    office_location: 'San Francisco',
    office_location_country: 'USA',
  },
  {
    id: '080',
    name: 'Clara Green',
    position: 'Social Media Coordinator',
    team: 'Marketing',
    office_location: 'London',
    office_location_country: 'UK',
  },
  {
    id: '081',
    name: 'Daniel Harris',
    position: 'Technical Consultant',
    team: 'IT',
    office_location: 'Singapore',
    office_location_country: 'Singapore',
  },
  {
    id: '082',
    name: 'Emily Clark',
    position: 'Human Resources Assistant',
    team: 'Human Resources',
    office_location: 'New York',
    office_location_country: 'USA',
  },
  {
    id: '083',
    name: 'Fred Johnson',
    position: 'Corporate Strategist',
    team: 'Strategy',
    office_location: 'Sydney',
    office_location_country: 'Australia',
  },
  {
    id: '084',
    name: 'Gina Young',
    position: 'Business Operations Manager',
    team: 'Operations',
    office_location: 'Toronto',
    office_location_country: 'Canada',
  },
  {
    id: '085',
    name: 'Hugo Lee',
    position: 'Brand Strategist',
    team: 'Marketing',
    office_location: 'Amsterdam',
    office_location_country: 'Netherlands',
  },
  {
    id: '086',
    name: 'Ivy Brown',
    position: 'Portfolio Manager',
    team: 'Finance',
    office_location: 'Zurich',
    office_location_country: 'Switzerland',
  },
  {
    id: '087',
    name: 'James Scott',
    position: 'Technical Architect',
    team: 'Development',
    office_location: 'Berlin',
    office_location_country: 'Germany',
  },
  {
    id: '088',
    name: 'Kylie Robinson',
    position: 'Customer Insights Manager',
    team: 'Analytics',
    office_location: 'Chicago',
    office_location_country: 'USA',
  },
  {
    id: '089',
    name: 'Liam Patel',
    position: 'User Experience Writer',
    team: 'Content',
    office_location: 'Dublin',
    office_location_country: 'Ireland',
  },
  {
    id: '090',
    name: 'Maya White',
    position: 'Creative Director',
    team: 'Design',
    office_location: 'Toronto',
    office_location_country: 'Canada',
  },
  {
    id: '091',
    name: 'Nico Adams',
    position: 'Software Tester',
    team: 'Quality Assurance',
    office_location: 'Los Angeles',
    office_location_country: 'USA',
  },
  {
    id: '092',
    name: 'Olivia Garcia',
    position: 'Public Relations Manager',
    team: 'Marketing',
    office_location: 'Tokyo',
    office_location_country: 'Japan',
  },
  {
    id: '093',
    name: 'Pauline Smith',
    position: 'Compliance Specialist',
    team: 'Legal',
    office_location: 'Berlin',
    office_location_country: 'Germany',
  },
  {
    id: '094',
    name: 'Quinton Kim',
    position: 'Sales Consultant',
    team: 'Sales',
    office_location: 'Austin',
    office_location_country: 'USA',
  },
  {
    id: '095',
    name: 'Renee Lee',
    position: 'Web Designer',
    team: 'Design',
    office_location: 'Vancouver',
    office_location_country: 'Canada',
  },
  {
    id: '096',
    name: 'Steve Patel',
    position: 'Data Privacy Officer',
    team: 'Legal',
    office_location: 'Sydney',
    office_location_country: 'Australia',
  },
  {
    id: '097',
    name: 'Tina Brooks',
    position: 'Training Coordinator',
    team: 'Human Resources',
    office_location: 'London',
    office_location_country: 'UK',
  },
  {
    id: '098',
    name: 'Uma Harrison',
    position: 'Risk Manager',
    team: 'Finance',
    office_location: 'Zurich',
    office_location_country: 'Switzerland',
  },
  {
    id: '099',
    name: 'Victor Thompson',
    position: 'Supply Chain Analyst',
    team: 'Operations',
    office_location: 'Chicago',
    office_location_country: 'USA',
  },
  {
    id: '100',
    name: 'Wendy Johnson',
    position: 'Healthcare Consultant',
    team: 'Consulting',
    office_location: 'Boston',
    office_location_country: 'USA',
  },
];
